/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.bank;

import javax.swing.JOptionPane;

/**
 *
 * @author Atish
 */
public class BankApp extends javax.swing.JFrame {
    BankControllerInterface bc;

    /**
     * Creates new form BankApp
     */
    public BankApp() {
        initComponents();
        bc = new BankControllerMYSQL();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jColorChooser1 = new javax.swing.JColorChooser();
        jColorChooser2 = new javax.swing.JColorChooser();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        menuExit = new javax.swing.JMenuItem();
        menuAccount = new javax.swing.JMenu();
        newAccount = new javax.swing.JMenuItem();
        deleteAccount = new javax.swing.JMenuItem();
        menuView = new javax.swing.JMenu();
        viewAllAcounts = new javax.swing.JMenuItem();
        transactionMenu = new javax.swing.JMenu();
        amountWithdraw = new javax.swing.JMenuItem();
        amountDeposit = new javax.swing.JMenuItem();
        fundTransfer = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CORE BANKING SYSTEM");
        setResizable(false);

        menuFile.setText("File");

        menuExit.setText("Exit");
        menuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuExitActionPerformed(evt);
            }
        });
        menuFile.add(menuExit);

        jMenuBar1.add(menuFile);

        menuAccount.setText("Account");

        newAccount.setText("New Account");
        newAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newAccountActionPerformed(evt);
            }
        });
        menuAccount.add(newAccount);

        deleteAccount.setText("Delete Account");
        deleteAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteAccountActionPerformed(evt);
            }
        });
        menuAccount.add(deleteAccount);

        jMenuBar1.add(menuAccount);

        menuView.setText("View");

        viewAllAcounts.setText("View All Acounts");
        viewAllAcounts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewAllAcountsActionPerformed(evt);
            }
        });
        menuView.add(viewAllAcounts);

        jMenuBar1.add(menuView);

        transactionMenu.setText("Transaction");

        amountWithdraw.setText("Withdraw");
        amountWithdraw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amountWithdrawActionPerformed(evt);
            }
        });
        transactionMenu.add(amountWithdraw);

        amountDeposit.setText("Deposit");
        amountDeposit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amountDepositActionPerformed(evt);
            }
        });
        transactionMenu.add(amountDeposit);

        fundTransfer.setText("Fund Transfer");
        fundTransfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fundTransferActionPerformed(evt);
            }
        });
        transactionMenu.add(fundTransfer);

        jMenuBar1.add(transactionMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 807, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 546, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuExitActionPerformed
        // TODO add your handling code here:
        int res = JOptionPane.showOptionDialog(this, "Do you want to Exit?", "Exit",JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null,new Object[] { "Yes", "No" }, JOptionPane.YES_OPTION);
        if (res == JOptionPane.YES_OPTION) {
           this.dispose();
        }
    }//GEN-LAST:event_menuExitActionPerformed

    private void newAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newAccountActionPerformed
        // TODO add your handling code here:
        NewAccountWindow naw = new NewAccountWindow(bc);
        this.add(naw);
        naw.setVisible(true);
    }//GEN-LAST:event_newAccountActionPerformed

    private void deleteAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteAccountActionPerformed
        // TODO add your handling code here:
        DeleteAccountWindow daw = new DeleteAccountWindow(bc);
        this.add(daw);
        daw.setVisible(true);
    }//GEN-LAST:event_deleteAccountActionPerformed

    private void viewAllAcountsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewAllAcountsActionPerformed
        // TODO add your handling code here:
        ViewAllAccountsWindow vaaw = new ViewAllAccountsWindow(bc);
        this.add(vaaw);
        vaaw.setVisible(true);
    }//GEN-LAST:event_viewAllAcountsActionPerformed

    private void amountWithdrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amountWithdrawActionPerformed
        // TODO add your handling code here:
        WithdrawWindow ww = new WithdrawWindow(bc);
        this.add(ww);
        ww.setVisible(true);
    }//GEN-LAST:event_amountWithdrawActionPerformed

    private void amountDepositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amountDepositActionPerformed
        // TODO add your handling code here:
        DepositWindow dw = new DepositWindow(bc);
        this.add(dw);
        dw.setVisible(true);
    }//GEN-LAST:event_amountDepositActionPerformed

    private void fundTransferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fundTransferActionPerformed
        // TODO add your handling code here:
        FundTransferWindow ftw = new FundTransferWindow(bc);
        this.add(ftw);
        ftw.setVisible(true);
    }//GEN-LAST:event_fundTransferActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem amountDeposit;
    private javax.swing.JMenuItem amountWithdraw;
    private javax.swing.JMenuItem deleteAccount;
    private javax.swing.JMenuItem fundTransfer;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JColorChooser jColorChooser2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuAccount;
    private javax.swing.JMenuItem menuExit;
    private javax.swing.JMenu menuFile;
    private javax.swing.JMenu menuView;
    private javax.swing.JMenuItem newAccount;
    private javax.swing.JMenu transactionMenu;
    private javax.swing.JMenuItem viewAllAcounts;
    // End of variables declaration//GEN-END:variables
}
