/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.bank;

import javax.swing.JOptionPane;

/**
 *
 * @author Atish
 */
public class DeleteAccountWindow extends javax.swing.JInternalFrame {
    BankControllerInterface bc;

    /**
     * Creates new form DeleteAccount
     */
    public DeleteAccountWindow(BankControllerInterface bc) {
        this.bc = bc;
        initComponents();
    }
    
    public DeleteAccountWindow(BankControllerInterface bc, int accNo)
    {
        this.bc = bc;
        initComponents();
        txtAccNo.setText(String.valueOf(accNo));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        txtAccNo = new javax.swing.JTextField();
        btnCancle = new javax.swing.JButton();
        btnAccountDetails = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();

        jButton4.setText("jButton4");

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Delete Account");

        jLabel1.setText("Enter Account Number to be deleted.");

        jLabel2.setText("Account Number:");

        btnCancle.setBackground(new java.awt.Color(255, 0, 0));
        btnCancle.setText("Cancle");
        btnCancle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancleActionPerformed(evt);
            }
        });

        btnAccountDetails.setBackground(new java.awt.Color(204, 255, 102));
        btnAccountDetails.setText("Account Details");
        btnAccountDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccountDetailsActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(0, 204, 0));
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(txtAccNo))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnCancle)
                                .addGap(18, 18, 18)
                                .addComponent(btnAccountDetails)
                                .addGap(18, 18, 18)
                                .addComponent(btnDelete)))
                        .addGap(0, 22, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtAccNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancle)
                    .addComponent(btnAccountDetails)
                    .addComponent(btnDelete))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancleActionPerformed
        // TODO add your handling code here:
        int res = JOptionPane.showOptionDialog(this, "Do you want to cancle?", "Cancle",JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null,new Object[] { "Yes", "No" }, JOptionPane.YES_OPTION);
        if (res == JOptionPane.YES_OPTION) {
           this.dispose();
        }
    }//GEN-LAST:event_btnCancleActionPerformed

    private void btnAccountDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccountDetailsActionPerformed
        // TODO add your handling code here:
        int res = JOptionPane.showOptionDialog(this, "Do you want View Account Details?", "View Account Details",JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null,new Object[] { "Yes", "No" }, JOptionPane.YES_OPTION);
        if (res == JOptionPane.YES_OPTION) 
        {
            Account a = bc.findAccount(Integer.parseInt(txtAccNo.getText()));
            AccountDetailsWindow adw = new AccountDetailsWindow(a, this);
            this.getParent().add(adw);
            adw.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_btnAccountDetailsActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
         int res = JOptionPane.showOptionDialog(this, "Do you want to Delete?", "Delete Account",JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null,new Object[] { "Yes", "No" }, JOptionPane.YES_OPTION);
        if (res == JOptionPane.YES_OPTION) 
        {
            int status = bc.delete(Integer.parseInt(txtAccNo.getText()));
            switch(status)
            {
                case 1:
                    JOptionPane.showMessageDialog(this, "Account Delete sucessful.", "Delete Account", JOptionPane.OK_OPTION);
                    this.dispose();
                    break;
                case -2:
                    JOptionPane.showMessageDialog(this, "Account Balance have some money, please withdraw first.", "Account have money", JOptionPane.OK_OPTION);
                    
                    int yon = JOptionPane.showOptionDialog(this, "Do you want to Withdraw Amount and delete your account?", "Yes or No",JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null,new Object[] { "Yes", "No" }, JOptionPane.YES_OPTION);
                    if (yon == JOptionPane.YES_OPTION) {
                        bc.withdraw(Integer.parseInt(txtAccNo.getText()), bc.findAccount(Integer.parseInt(txtAccNo.getText())).getAmount());
                        bc.delete(Integer.parseInt(txtAccNo.getText()));
                        JOptionPane.showMessageDialog(this, "Account Delete sucessful.", "Delete Account", JOptionPane.OK_OPTION);
                        this.dispose();
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(this, "Account Not Delete.", "Account Not Delete", JOptionPane.OK_OPTION);
                        txtAccNo.setText("");
                        txtAccNo.grabFocus();
                        break;
                    }
                    break;

                case -1:
                    JOptionPane.showMessageDialog(this, "Delete function in database didn't go well..", "SQL Erroe", JOptionPane.OK_OPTION);
                    this.dispose();
                    break;
                    
                case 0:
                    JOptionPane.showMessageDialog(this, "Account not found!!", "Account not found", JOptionPane.OK_OPTION);
                    txtAccNo.setText("");
                    txtAccNo.grabFocus();
                    break;
            }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccountDetails;
    private javax.swing.JButton btnCancle;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField txtAccNo;
    // End of variables declaration//GEN-END:variables
}
