/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.bank;

import javax.swing.JOptionPane;

/**
 *
 * @author Atish
 */
public class FundTransferWindow extends javax.swing.JInternalFrame {
    BankControllerInterface bc;

    /**
     * Creates new form FundTransferWindow
     */
    public FundTransferWindow(BankControllerInterface bc) {
        this.bc = bc;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTextField3 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtScrAccNo = new javax.swing.JTextField();
        txtTrgAccNo = new javax.swing.JTextField();
        btnCancle = new javax.swing.JButton();
        btnDetailsOfScr = new javax.swing.JButton();
        btnTransfer = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtAmountToTransfer = new javax.swing.JTextField();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jTextField3.setText("jTextField3");

        jButton4.setText("jButton4");

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Inter Account Fund Transfer");

        jLabel1.setText("Enter details for Inter Account Fund Transfer.");

        jLabel2.setText("Account Number of Source:");

        jLabel3.setText("Account Number of Traget:");

        txtScrAccNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtScrAccNoActionPerformed(evt);
            }
        });

        btnCancle.setBackground(new java.awt.Color(255, 0, 0));
        btnCancle.setText("Cancle");
        btnCancle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancleActionPerformed(evt);
            }
        });

        btnDetailsOfScr.setBackground(new java.awt.Color(204, 255, 102));
        btnDetailsOfScr.setText("Source Account Details");
        btnDetailsOfScr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetailsOfScrActionPerformed(evt);
            }
        });

        btnTransfer.setBackground(new java.awt.Color(0, 204, 0));
        btnTransfer.setText("Transfer");
        btnTransfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransferActionPerformed(evt);
            }
        });

        jLabel4.setText("Amount to Transfer:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel1)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtScrAccNo, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel4))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtTrgAccNo)
                                        .addComponent(txtAmountToTransfer, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnCancle)
                                .addGap(18, 18, 18)
                                .addComponent(btnDetailsOfScr)
                                .addGap(18, 18, 18)
                                .addComponent(btnTransfer)))
                        .addGap(0, 38, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtScrAccNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTrgAccNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtAmountToTransfer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancle)
                    .addComponent(btnDetailsOfScr)
                    .addComponent(btnTransfer))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtScrAccNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtScrAccNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtScrAccNoActionPerformed

    private void btnCancleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancleActionPerformed
        // TODO add your handling code here:
        int res = JOptionPane.showOptionDialog(this, "Do you want to cancle?", "Cancle",JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null,new Object[] { "Yes", "No" }, JOptionPane.YES_OPTION);
        if (res == JOptionPane.YES_OPTION) {
           this.dispose();
        }
    }//GEN-LAST:event_btnCancleActionPerformed

    private void btnDetailsOfScrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetailsOfScrActionPerformed
        // TODO add your handling code here:
        int res = JOptionPane.showOptionDialog(this, "Do you want View Account Details?", "View Account Details",JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null,new Object[] { "Yes", "No" }, JOptionPane.YES_OPTION);
        if (res == JOptionPane.YES_OPTION) 
        {
            Account a = bc.findAccount(Integer.parseInt(txtScrAccNo.getText()));
            AccountDetailsWindow adw = new AccountDetailsWindow(a, this);
            this.getParent().add(adw);
            adw.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_btnDetailsOfScrActionPerformed

    private void btnTransferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransferActionPerformed
        // TODO add your handling code here:
        int res = JOptionPane.showOptionDialog(this, "Do you want to cancle?", "Cancle",JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null,new Object[] { "Yes", "No" }, JOptionPane.YES_OPTION);
        if (res == JOptionPane.YES_OPTION) 
        {
           int status = bc.fundTransfer(Integer.parseInt(txtTrgAccNo.getText()), Integer.parseInt(txtScrAccNo.getText()), Integer.parseInt(txtAmountToTransfer.getText()));
           switch (status) 
            {
                case 1:
                    JOptionPane.showMessageDialog(this, "A Funds Transferred sucessfuliy!!", "Fund Transferred", JOptionPane.OK_OPTION);
                    this.dispose();
                    break;
                case -1:
                    JOptionPane.showMessageDialog(this, "Source account dosn't exists.", "Source Account Not Found", JOptionPane.OK_OPTION);
                    txtScrAccNo.setText("");
                    txtScrAccNo.grabFocus();
                    break;
                case -2:
                    JOptionPane.showMessageDialog(this, "Target account dosn't exists.", "Target Account Not Found", JOptionPane.OK_OPTION);
                    txtTrgAccNo.setText("");
                    txtTrgAccNo.grabFocus();
                    break;
                case -3:
                    JOptionPane.showMessageDialog(this, "The source fund doesn't have the required balance.", "Less Balance", JOptionPane.OK_OPTION);
                    txtAmountToTransfer.setText("");
                    txtAmountToTransfer.grabFocus();
                    break;
                case 0:
                    JOptionPane.showMessageDialog(this, "Delete function in database didn't go well..", "SQL Error", JOptionPane.OK_OPTION);
                    this.dispose();
                    break;
            }
        }
    }//GEN-LAST:event_btnTransferActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancle;
    private javax.swing.JButton btnDetailsOfScr;
    private javax.swing.JButton btnTransfer;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField txtAmountToTransfer;
    private javax.swing.JTextField txtScrAccNo;
    private javax.swing.JTextField txtTrgAccNo;
    // End of variables declaration//GEN-END:variables
}
